# Generated by Django 2.1 on 2018-11-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_auto_20180809_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='waktu_download',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
